services:

  login-server:
    image: hxhieu/l2j-server-login
    container_name: l2j-server-login
    ports:
      # gameserver listener, only expose when login and game are on different hosts
      - 9014:9014
      # gameclient listener
      - 2106:2106
    environment:
      # variables required on first startup to initialize the database
      # - L2JLOGIN_DB_INIT=1
      # - L2JLOGIN_DB_HOST=${DB_SERVER_HOST}
      # - L2JLOGIN_DB_PORT=${DB_SERVER_PORT}
      # - L2JLOGIN_DB_USER=${DB_USER_NAME}
      # - L2JLOGIN_DB_PASS=${DB_USER_PASSWORD}
      # - L2JLOGIN_DB_NAME=l2jls
      # - L2JLOGIN_DB_INSTALL_USER=${DB_USER_NAME}
      # - L2JLOGIN_DB_INSTALL_PASS=${DB_USER_PASSWORD}
      # variables required after initial start or custom config files in the mapped volume for custom data
      - L2JLOGIN_server_GameServerHost=*
      - L2JLOGIN_database_URL=${DB_SERVER_ADDRESS}/l2jls
      - L2JLOGIN_database_User=${DB_USER_NAME}
      - L2JLOGIN_database_Password=${DB_USER_PASSWORD}
    volumes:
      - ../_live/server-login/logs:/opt/l2j/deploy/login/logs:rw
      - ../_live/server-login/custom-data:/opt/l2j/custom/login:rw

  game-server:
    # previously build with ./make_docker_image.sh
    image: hxhieu/l2j-server-game
    container_name: l2j-server-game
    ports:
      # gameclient listener
      - 7777:7777
    environment:
      # variables required on first startup to initialize the database
      # - L2JGAME_DB_INIT=1
      # - L2JGAME_DB_HOST=${DB_SERVER_HOST}
      # - L2JGAME_DB_PORT=${DB_SERVER_PORT}
      # - L2JGAME_DB_USER=${DB_USER_NAME}
      # - L2JGAME_DB_PASS=${DB_USER_PASSWORD}
      # - L2JGAME_DB_NAME=l2jgs
      # - L2JGAME_DB_INSTALL_USER=${DB_USER_NAME}
      # - L2JGAME_DB_INSTALL_PASS=${DB_USER_PASSWORD}
      # variables required after initial start or custom config files in the mapped volume for custom data
      - L2JGAME_database_URL=${DB_SERVER_ADDRESS}/l2jgs
      - L2JGAME_database_User=${DB_USER_NAME}
      - L2JGAME_database_Password=${DB_USER_PASSWORD}
      # Connect to loginserver on this host and port
      - L2JGAME_server_LoginHost=login-server
      - L2JGAME_server_LoginPort=9014
      # # Characters
      # - L2JGAME_character_Delevel=${L2JGAME_character_Delevel}
      # - L2JGAME_character_WeightLimit=${L2JGAME_character_WeightLimit}
      # - L2JGAME_character_DeathPenaltyChance=${L2JGAME_character_DeathPenaltyChance}
      # - L2JGAME_character_HpRegenMultiplier=${L2JGAME_character_HpRegenMultiplier}
      # - L2JGAME_character_MpRegenMultiplier=${L2JGAME_character_MpRegenMultiplier}
      # - L2JGAME_character_CpRegenMultiplier=${L2JGAME_character_CpRegenMultiplier}
      # - L2JGAME_character_MaxPlayerLevel=${L2JGAME_character_MaxPlayerLevel}
      # - L2JGAME_character_MaxSubclass=${L2JGAME_character_MaxSubclass}
      # - L2JGAME_character_MaxSubclassLevel=${L2JGAME_character_MaxSubclassLevel}

      # # Rates
      # - L2JGAME_rates_DeathDropAmountMultiplier=${L2JGAME_rates_DeathDropAmountMultiplier}
      # - L2JGAME_rates_CorpseDropAmountMultiplier=${L2JGAME_rates_CorpseDropAmountMultiplier}
      # - L2JGAME_rates_HerbDropAmountMultiplier=${L2JGAME_rates_HerbDropAmountMultiplier}
      # - L2JGAME_rates_RaidDropAmountMultiplier=${L2JGAME_rates_RaidDropAmountMultiplier}
      # - L2JGAME_rates_RateSp=${L2JGAME_rates_RateSp}
      # - L2JGAME_rates_RatePartySp=${L2JGAME_rates_RatePartySp}
      # - L2JGAME_rates_RateQuestRewardAdena=${L2JGAME_rates_RateQuestRewardAdena}
      # - L2JGAME_rates_UseQuestRewardMultipliers=${L2JGAME_rates_UseQuestRewardMultipliers}
      # - L2JGAME_rates_RateQuestReward=${L2JGAME_rates_RateQuestReward}
      # - L2JGAME_rates_PetXpRate=${L2JGAME_rates_PetXpRate}
    volumes:
      - ../_live/server-game/logs:/opt/l2j/deploy/game/logs:rw
      - ../_live/server-game/custom-data:/opt/l2j/custom/game:rw
      - ./config/ipconfig.xml:/opt/l2j/deploy/game/config/ipconfig.xml:r
      - ./config/character.properties:/opt/l2j/deploy/game/config/character.properties:r
      - ./config/rates.properties:/opt/l2j/deploy/game/config/rates.properties:r
